inherit_from: .rubocop_todo.yml
AllCops:
  Exclude:
    - 'tracks/**/*'
    - 'test/fixtures/**/*'
    - 'bin/*'
    - 'vendor/**/*'
    - 'api/v1/routes/exercises.rb'
Style/StringLiterals:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
Style/BlockDelimiters:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/Documentation:
  Exclude:
    - 'test/**/*'
    - 'api/**/*'
    - 'api/**/*'
Style/RaiseArgs:
  Enabled: true
  EnforcedStyle: compact
Style/AndOr:
  Enabled: true
  EnforcedStyle: conditionals
Style/FormatString:
  Enabled: true
  EnforcedStyle: percent
Style/GuardClause:
  Enabled: false
Lint/RescueException:
  Exclude:
    - 'api/helpers/errors.rb'
Metrics/LineLength:
  Max: 120
  AllowURI: true
  URISchemes:
    - http
    - https
  Exclude:
    - 'test/**/*'
Metrics/MethodLength:
  Exclude:
    - 'test/**/*'
Metrics/AbcSize:
  Exclude:
    - 'test/**/*'
Metrics/ClassLength:
  Max: 130
